name: Test and Deploy FastAPI App

on:
  pull_request:
    branches:
      - main  # Runs on PRs targeting the main branch

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"  # Use the required Python version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: pytest  # Runs tests; the PR cannot be merged if it fails

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: test  # Only runs if tests pass
    if: github.event_name == 'pull_request' && github.event.action == 'closed'  # Only runs when the PR is merged

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to Server
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_USER@54.245.237.108 <<EOF
            cd /home/emeka/fastapi-book-project
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            systemctl restart fastapi-book-project
          EOF